### ISSUE TITLE
errors in log after dying in hardcore. lagging back at the title screen

### ISSUE THREAD

**Issue by mattrix444** [CyclopsMC/EverlastingAbilities#122]
#### Issue type:

- :snail: lag after dying and returning to title.

____

#### Short description:

i get a log full of errors mentioning everlasting abilities whenever i die in hardcore and return to the title screen. here is a snippet of what its saying.

"java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
    at org.cyclops.everlastingabilities.network.packet.SendAbilityStorePacket.actionClient(SendAbilityStorePacket.java:47)
    at org.cyclops.cyclopscore.network.PacketHandler$HandlerClient$1.run(PacketHandler.java:134)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.minecraft.util.Util.runTask(SourceFile:529)"

#### Steps to reproduce the problem:

1. die in hardcore,
2. press return to title...
3. wait for lag to finish :)

____

#### Versions:

- This mod: 1.5.0
- Minecraft: 1.12.2
- Forge: 14.23.5.2836

#### Profiler output:

cant really profile as i am at the title screen. also not really sure the problem is causing the lag or something in relation to the mod is. thanks :)

**Comment by rubensworks** [comment]
Thanks for reporting!

Note to self: in hardcore worlds, the world may be null when the packet is received: https://github.com/CyclopsMC/EverlastingAbilities/blob/master-1.12/src/main/java/org/cyclops/everlastingabilities/network/packet/SendAbilityStorePacket.java#L47

<blockquote><img src="https://avatars2.githubusercontent.com/u/11808375?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/EverlastingAbilities">CyclopsMC/EverlastingAbilities</a></strong></div><div>Entry for The Modding Trials 2016. Contribute to CyclopsMC/EverlastingAbilities development by creating an account on GitHub.</div></blockquote>

**Comment by mattrix444** [comment]
No worries buddy. Thought it would be best to mention. Still a great mod. Thanks
