### ISSUE TITLE
Minecraft crashed when entering a world

### ISSUE THREAD

**Issue by 2781762845** [CyclopsMC/EverlastingAbilities#156]
This is my game report.The game version is 1.12.2
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2020-01-30 22:26:13 CST
Description: Ticking player

java.lang.ClassCastException: net.minecraft.entity.player.EntityPlayerMP cannot be cast to net.minecraft.entity.passive.EntityAnimal
    at org.cyclops.everlastingabilities.ability.AbilityTypeFertility.onTick(AbilityTypeFertility.java:34)
    at org.cyclops.everlastingabilities.ability.AbilityTypeRegistry.onLivingUpdate(AbilityTypeRegistry.java:74)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1143_AbilityTypeRegistry_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:581)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2095)
    at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:234)
    at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:382)
    at net.minecraft.network.NetHandlerPlayServer.update(NetHandlerPlayServer.java:173)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:209)
    at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285)
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:180)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Player being ticked --
  Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
  Entity ID: 1349
  Entity Name: xuexiaole
  Entity's Exact location: 790.18, 88.00, 129.08
  Entity's Block location: World: (790,88,129), Chunk: (at 6,5,1 in 49,8; contains blocks 784,0,128 to 799,255,143), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
  Entity's Momentum: 0.00, -0.08, 0.00
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Ticking connection --
  Connection: net.minecraft.network.NetworkManager@6a09fa7d

**Comment by rubensworks** [comment]
Please fill in the proper issue template. I am missing information that is required to resolve this issue.
